一括インストールスクリプトのページの改訂(再PR用)
OpenRTM/openrtm.org pull request #106
Opened 2019-11-28 04:37 UTC by kkunita

## Identify the Bug

Link to the issue describing the bug that you're fixing.  
If there is not yet an issue for your bug, please open a new issue and then link to that issue in your pull request.

## Description of the Change

新方針に合わせての再PR
変更点は
- コマンドライン書式の変更(使えないものを極力わかるようにした)
- 文書構造の変更
- インストールされるパッケージの表のPNGファイルを変更
## Verification 

- [X] Did you check grammar?  (ex. https://www.grammarly.com/, https://www.kiji-check.com/) 
- [X] Did you check pukiwiki grammar?
- [ ] Did you check Japanese-English consistency?

2019-12-03 05:35 UTC, n-ando requested changes
コマンドプロンプトの$は半角でお願いします。

2019-12-03 10:20 UTC, kkunita commented
修正しました。

2019-12-04 23:08 UTC, n-ando requested changes
スクリプトのURLをリンクにしてください。

2019-12-05 01:35 UTC, kkunita commented
リンクにすると、クリックしたらwgetしたりDownloadするようにはできなくて、シェルスクリプトの内容が画面に表示されてしまうので、かえって不便です。ですので、あえてリンクしないようにしました。本当はURLだけを整形テキストではない形でリンクもしない形で見せる方法かあるか、リンクをクリックしたらDownloadするようにできるとそれが良いのですが、それができないので、こんな形になっています。インストラクション上は後でURLをいれてwgetするようになっているので、URLのCut&Pasteが一番やりやすい方法としてこういう形に変更しています。

2019-12-05 01:41 UTC, n-ando commented
リンクになっていると、右クリックでURLをコピーできるので便利ですので、リンクにしてください。
よろしくお願いいたします。

2019-12-05 01:43 UTC, n-ando commented
左クリックしないように、「右クリックでファイルを保存、URLのコピー等を選んでください。」など書いておくといいかもしれません。

2019-12-05 02:34 UTC, kkunita commented
修正しました。

2019-12-05 06:03 UTC, n-ando approved these changes

2019-12-05 06:03 UTC, merged