OpenRTM付属サンプルについてのページの改訂
OpenRTM/openrtm.org pull request #179
Opened 2020-01-15 08:36 UTC by kkunita

## Identify the Bug

Link to the issue describing the bug that you're fixing.  
If there is not yet an issue for your bug, please open a new issue and then link to that issue in your pull request.

## Description of the Change

* Name Serviceがインストールされていないのは削除、rtc-namingはrtm-namingに変更
* 試用はニュアンスが違うの「使ってみる」等の表現に変更
* 細かい表現の修正
* リンクが切れていたので、修正

## Verification 

- [X] Did you check grammar?  (ex. https://www.grammarly.com/, https://www.kiji-check.com/) 
- [X] Did you check pukiwiki grammar?
- [X] Did you check Japanese-English consistency?

2020-01-19 04:01 UTC, n-ando requested changes
USBCameraMonitor / USBCameraAcquire を現在の名前 (OpenCVCamera と CameraViewer) に修正してください。

2020-01-19 04:03 UTC, n-ando requested changes
Installing OpenRTP> // en / node / 6655 の記述の部分はURL aliasに変更してください。

2020-01-20 04:45 UTC, kkunita commented
OpenCV関係の名前の変更と、英語版のOpenRTPのページへのリンクアドレスを変更しました。リンク先アドレスはNode番号指定のままにしておきます。(リンク先のURL Aliasがページ構造の変更などの理由で変更された場合にリンク切れをおこし、その修正をするためにはリンク元のページが全部わからないといけないため、Node番号でDrupal内のリンク先は指定して、ページのURL Aliasの変更の影響を受けないようにしています。)　もしそのリスクを考慮してもURL Aliasの方が良いのであれば、そちらにあとでまとめて変更しますので指示してください。

2020-01-21 02:54 UTC, n-ando commented
URL Aliasだと、日本語・英語ページの切り替えが自動に行われたように思います。ご確認ください。
また、ノード番号だとそのページそのものになり、更新に伴いべーつページを移した場合などにリンク切れとなるように思います。URL Aliasを一応すべてのページに定義しているので、Aliasを用いるのが良いと思います。

2020-01-21 07:37 UTC, kkunita commented
日本語、英語の切り替えでは、同じアドレスが使えてページ英語版と日本語版のリンク先は先頭の//EN/を//JA/に変えるだけで済むので便利なのですが、問題は、あるページを構成を変えて、例えばinstallation/install_1_2/bulk_installのページをinstallation/common/bulk_install
のページに移動した場合、このbulk_installにリンクしているページを全部見つけ出して修正しないといけないというのが問題です。リンク先は簡単に見つけられるのですが、リンク元を見つけるのはかなり難しく、documentmenu_ja.txt/documentmenu_ja.mdが唯一の手掛かりなって、しかも現状GitHubの使い方だとdocumentmenu_ja.txt/documentmenu_ja.mdのアップデートはタイムリーにできないので、結構間違いが含まれていたりします。そうすると、Webサイトのそのページにリンクしてそうなページを全部見てみて、再確認をするような作業が必要になってしまって、その移動したページにリンクしてそうなページにアクセスしてその中のリンクをチェックするという作業が必要になります。

一方node番号で指定した場合は、リンク元のページを編集しているときに、正しくリンクされていて、いったん正しいページが作れれば、ページの置き場所をかえてURL Aliasがどう変わろうともリンク切れはおこりません。大幅な変更がページにある場合や古いページをのこして、新規ページを作るような場合は、たしかにNodeが新しくできるので、URLを使ったケースと同じようにリンク元を見つけ出さないといけないのですが、その場合も、新規Nodeに古いページを書いて、既存ノードを新しいページとすることで対処できます。

ただ、リンク先として単なる数字になるので、実際にページを見てみないと正しいページにリンクされているかどうかわからないのと、リンク先を指定する時にそのノード番号を別途見つける必要があるのが不便で結構面倒なので、ページを作成編集するうえではURL Aliasを使ったほうが確かに楽でページの内容をGitHub上のテキストでチェックもしやすいのです。

それぞれ短所/長所があるのですが、検討した結果、後々の編集でリンク切れを起こさないことを優先して、ページ作成時の不便さには目をつぶることにしました。

なお、現状ではリンクはノード番号で全てしています。

リンク元を自動的に見つけ出すようなツールがあると良いのですが..

とにかく現状ではノード番号を使っているので、これを直すのは、かなり手間で、しかも間違いがかなり入る可能性があります。

どうしてもURL Aliasベースにしたい場合は、だいたいのページが完成してURL Aliasの変更がもう起こらない状態にしてからGitHub上リンク変更のためのブランチを作りページごとではなくDocumentmenu_jaとページの編集を一気にするような形で、リンクをノード番号からURL Aliasに一気に直すような方法をとりたいです。

ただ一応ちゃんとしているページを再チェックしながらの作業で特に新しい情報も付け加えるわけではないので、あまりやりたくはないです。

でもやる場合は、どこか切れが良いところで一気にという形にしたいです。例えば、インストールがらみページがもう少しで終わるので、そのタイミングで英語版のページを(実際に英語化するか別にして一応言語属性とタイトルだけは英語になっているページを)作りながらというので行きたいです。ただ時間が結構かかるので、優先順位としては良いでしょうか？　

2020-01-21 08:46 UTC, n-ando approved these changes

2020-01-21 08:46 UTC, n-ando commented
了解です。では、Approve、マージします。

2020-01-21 08:46 UTC, merged