Opencvcamera
OpenRTM/openrtm.org pull request #188
Opened 2020-01-20 08:56 UTC by kkunita

## Identify the Bug

Link to the issue describing the bug that you're fixing.  
If there is not yet an issue for your bug, please open a new issue and then link to that issue in your pull request.

## Description of the Change

* 翻訳の修正
* 細かい表現の修正
* Batファイルの実行に変更
* ファイル名の変更
 

## Verification 

- [X] Did you check grammar?  (ex. https://www.grammarly.com/, https://www.kiji-check.com/) 
- [X] Did you check pukiwiki grammar?
- [X] Did you check Japanese-English consistency?

2020-01-21 09:48 UTC, n-ando requested changes
OpenRTM-aistのC++版Linuxパッケージや、Python版、Java版には付属していませんのでご注意ください。
↓
OpenRTM-aistのPython版、Java版には付属していませんのでご注意ください。また、Linux上では、OpenRTM-aist のパッケージリポジトリで提供されている ImageProcessing パッケージを別途インストールする必要があります。

のように変更してください。

2020-01-22 03:01 UTC, kkunita commented
Image Processing Packageがある、OpenRTM-aistのパッケージリポジトリってどこにありますか？　また、Webサイト上でどっかで説明されていますか？https://github.com/OpenRTM/ImageProcessing/releases
ですか？

2020-01-24 04:37 UTC, n-ando commented
説明するところは特段ないので、ここでざっくり説明してください。

2020-01-29 09:14 UTC, kkunita commented
別ページにLinuxにおけるBuild手順を付け加えることにしました。
そして、他のサンプルコンポーネントの説明も追加しました

2020-02-04 08:32 UTC, n-ando approved these changes

2020-02-04 08:32 UTC, merged