Rtcb rtse debug
OpenRTM/openrtm.org pull request #191
Opened 2020-01-21 05:12 UTC by kkunita

## Identify the Bug

Link to the issue describing the bug that you're fixing.  
If there is not yet an issue for your bug, please open a new issue and then link to that issue in your pull request.

## Description of the Change

* 強制改行　の削除
* 一般ユーザ－不必要の旨のメッセージ追加

## Verification 

- [X] Did you check grammar?  (ex. https://www.grammarly.com/, https://www.kiji-check.com/) 
- [X] Did you check pukiwiki grammar?
- [ ] Did you check Japanese-English consistency?

2020-01-21 11:02 UTC, n-ando requested changes
本ページはRTCBuilder/RTSystemEditorの開発・デバッグに関する情報を記したページです。EclipseにおけるPlugin開発の知識が必要になります。

RTCBuilderとRTSystemEditorを利用するのみであれば、このページの情報は不要です。
OpenRTP （RTCBuilder、RTSystemEditor）をインストールして使用するための情報は[[インストーラによるインストール>//ja/node/6938]]を参照してしてください。

としてください。

2020-01-22 02:19 UTC, kkunita commented
修正要求反映しました。

2020-01-24 04:38 UTC, n-ando approved these changes

2020-01-24 04:38 UTC, n-ando approved these changes

2020-01-24 04:38 UTC, merged