ImageSubstraction　のページ追加
OpenRTM/openrtm.org pull request #199
Opened 2020-01-29 09:17 UTC by kkunita

## Identify the Bug

Link to the issue describing the bug that you're fixing.  
If there is not yet an issue for your bug, please open a new issue and then link to that issue in your pull request.

## Description of the Change

* ImageSubstractionのページを追加
* 現状Windows版が動かない旨も説明

## Verification 

- [X] Did you check grammar?  (ex. https://www.grammarly.com/, https://www.kiji-check.com/) 
- [X] Did you check pukiwiki grammar?
- [X] Did you check Japanese-English consistency?

2020-02-04 08:37 UTC, n-ando requested changes
SubstractはSubtractに修正してください。よろしくお願いします。

2020-02-04 09:05 UTC, kkunita commented
Slackでも書きましたが、Substractでも英語古語として正しいようです。あと、修正にはリリースがいると思いますが、リリース後の修正の方が良いかとは思いますが、リリースまたずに修正しても良いですか、SubstractCaptureImageの方も同様で、SubtractCaptureImageに直す必要があります。どちらもリリース待たずに直して良いですか？　SubstractCaptureImageはGitHubのソースも直しますか？　Batchファイルの修正とかも必要で、そっちはGitHub側にないようなので(未確認です)、どうしたものかと思っています。

2020-02-13 08:23 UTC, n-ando requested changes
ImageSubscription -> ImageSubtraction?

2020-02-13 09:37 UTC, kkunita commented
Substraction/SubscriptionからSubtractionへの変更とファイル名ディレクトリ名の変更しました。

2020-02-17 04:32 UTC, n-ando approved these changes

2020-02-17 04:32 UTC, merged