Python 1.2系 Raspbianへのインストール のページの修正(post_install_rtshellの追加と細かい修正)と英…
OpenRTM/openrtm.org pull request #220
Opened 2020-03-03 02:06 UTC by kkunita

…語化ページの作成

## Identify the Bug

Link to the issue describing the bug that you're fixing.  
If there is not yet an issue for your bug, please open a new issue and then link to that issue in your pull request.

## Description of the Change

* rtshell_post_installの追加
* SDメモリーカード　を　SDカード　に変更(文法チェックの結果メモリーをメモリに変更することが推奨されたので、その場合の違和感があったためSDカードに変更)
* OpenRTM-aistをOpenRTM-aist-Pythonに変更

## Verification 

- [X] Did you check grammar?  (ex. https://www.grammarly.com/, https://www.kiji-check.com/) 
- [X] Did you check pukiwiki grammar?
- [X] Did you check Japanese-English consistency?

2020-03-03 13:53 UTC, n-ando commented on documents/02_installation/01_install_1_2/02_python_1_2/03_raspbian_python_1_2/03_raspbian_python_1_2_en.txt
> +OpenRTM-aist-Python is provided with deb packages for Raspbian for Raspberry Pi. Please note that support for Raspbian and its versions are subject to change or suspension without notice.
Raspbian for Raspberry Pi -> Raspbian for the Raspberry Pi

2020-03-03 14:02 UTC, n-ando commented on documents/02_installation/01_install_1_2/02_python_1_2/03_raspbian_python_1_2/03_raspbian_python_1_2_en.txt
> +Download the Rasbian image from the following link and write it to the SD card. The capacity of the SD card should be more than 4GB. For the method to write the image to an SD card, refer to [[RPi Ea
the Rasbian image <- which image?
リンク先のページにはいくつかイメージがあるので、明示しておいた方がいいと思います。
でなければ the は適切でないと思います。
また、リンクも、../download/ だとThird partyイメージもあってわかりにくいので
https://www.raspberrypi.org/downloads/raspbian/
を示してあげた方がいいかも。

Download one of the Rasbian images from the following link and write it to the SD card.

:中略

- [[Raspbian Buster Download:https://www.raspberrypi.org/raspbian/]]

2020-03-03 14:03 UTC, n-ando commented on documents/02_installation/01_install_1_2/02_python_1_2/03_raspbian_python_1_2/03_raspbian_python_1_2_ja.txt
>  - [[Raspberry Pi Downloads:https://www.raspberrypi.org/downloads/]]
リンクはこちらの方がいいかも

- [[Raspbian Buster Download:https://www.raspberrypi.org/raspbian/]]

2020-03-03 14:04 UTC, n-ando requested changes
コメントに従って修正をお願いします。

2020-03-04 01:56 UTC, kkunita commented
修正しました。

2020-03-11 08:15 UTC, n-ando approved these changes

2020-03-11 08:15 UTC, merged