C++1.2系　Windowsへのインストールのページの英語化
OpenRTM/openrtm.org pull request #221
Opened 2020-03-03 07:10 UTC by kkunita

## Identify the Bug

Link to the issue describing the bug that you're fixing.  
If there is not yet an issue for your bug, please open a new issue and then link to that issue in your pull request.

## Description of the Change

1.2系C++ Windowsへのインストール下のファイルの英語化

## Verification 

- [X] Did you check grammar?  (ex. https://www.grammarly.com/, https://www.kiji-check.com/) 
- [X] Did you check pukiwiki grammar?
- [X] Did you check Japanese-English consistency?

2020-03-03 14:08 UTC, n-ando commented on documents/02_installation/01_install_1_2/01_cpp_1_2/01_install_windows_1_2/01_install_windows_1_2_en.txt
> +The procedure for installing OpenRTM-aist using the msi installer is described on the following page.
the msi installer -> the MSI (Microsoft Windows Installer, with .msi extention) executable

MSI とするときは大文字で、拡張子の場合は .msi として統一しておいてください。

2020-03-03 14:10 UTC, n-ando requested changes
コメントに従って修正お願いします。

2020-03-04 02:08 UTC, kkunita commented
このページは修正しました。他のページは別途PRします。

2020-03-04 03:11 UTC, kkunita commented
修正しました。

2020-03-12 00:57 UTC, n-ando approved these changes

2020-03-12 00:57 UTC, merged