C++ 1.2系　Ubutu/Debianへのインストール　のページの英語化と追加修正
OpenRTM/openrtm.org pull request #222
Opened 2020-03-03 08:18 UTC by kkunita

## Identify the Bug

Link to the issue describing the bug that you're fixing.  
If there is not yet an issue for your bug, please open a new issue and then link to that issue in your pull request.

## Description of the Change

* 英語化
* 細かい修正

## Verification 

- [X] Did you check grammar?  (ex. https://www.grammarly.com/, https://www.kiji-check.com/) 
- [X] Did you check pukiwiki grammar?
- [X] Did you check Japanese-English consistency?

2020-03-03 14:11 UTC, n-ando commented on documents/02_installation/01_install_1_2/01_cpp_1_2/02_install_ubuntu_1_2/02_install_ubuntu_1_2_en.txt
> +The C ++ version of OpenRTM-aist provides a deb package that can be used on Ubuntu and Debian GNU Linux.
C ++ -> C++

2020-03-03 14:14 UTC, n-ando commented on documents/02_installation/01_install_1_2/01_cpp_1_2/02_install_ubuntu_1_2/02_install_ubuntu_1_2_en.txt
> + $ sudo sh pkg_install_ubuntu.sh -l c ++ --yes
c ++ -> c++

2020-03-03 14:14 UTC, n-ando commented on documents/02_installation/01_install_1_2/01_cpp_1_2/02_install_ubuntu_1_2/02_install_ubuntu_1_2_en.txt
> + # sh pkg_install_debian.sh -l c ++ --yes
c ++ -> c++

2020-03-03 14:15 UTC, n-ando requested changes
コメントに従って修正お願いいたします。

2020-03-04 03:17 UTC, kkunita commented
修正しました。

2020-03-12 00:59 UTC, n-ando approved these changes

2020-03-12 00:59 UTC, merged