Install windows python12
OpenRTM/openrtm.org pull request #237
Opened 2020-03-19 07:27 UTC by kkunita

## Identify the Bug

Link to the issue describing the bug that you're fixing.  
If there is not yet an issue for your bug, please open a new issue and then link to that issue in your pull request.

## Description of the Change

* 英語化
* 文構造の修正

## Verification 

- [X ] Did you check grammar?  (ex. https://www.grammarly.com/, https://www.kiji-check.com/) 
- [X] Did you check pukiwiki grammar?
- [X] Did you check Japanese-English consistency?

2020-03-21 12:28 UTC, n-ando requested changes

2020-03-21 12:28 UTC, n-ando commented on documents/02_installation/01_install_1_2/02_python_1_2/01_windows_python_1_2/01_windows_python_1_2_ja.txt
> +--- 64bit用msi利用時のPATHへの追加設定
MSI

2020-03-21 12:28 UTC, n-ando commented on documents/02_installation/01_install_1_2/02_python_1_2/01_windows_python_1_2/01_windows_python_1_2_ja.txt
> +--- 32bit用msi利用時の環境変数
MSI

2020-03-23 07:03 UTC, kkunita commented on documents/02_installation/01_install_1_2/02_python_1_2/01_windows_python_1_2/01_windows_python_1_2_ja.txt
> +--- 32bit用msi利用時の環境変数
修正しました。ここからリンクされているファイルでも同じように小文字のmsiを使っているところがあったので修正し、いっしょにPushしました。

2020-03-23 08:40 UTC, n-ando approved these changes

2020-03-23 08:40 UTC, merged