Java版1.2系 動作確認(Windows編) のページの修正(常体->敬体等)と英語化
OpenRTM/openrtm.org pull request #249
Opened 2020-03-25 05:12 UTC by kkunita-work

## Identify the Bug

Link to the issue describing the bug that you're fixing.  
If there is not yet an issue for your bug, please open a new issue and then link to that issue in your pull request.

## Description of the Change
* 一部常体だったのを敬体に変更
* バッチファイルがコンポーネントを起動する意味の説明に変更
* 英語化

## Verification 

- [X] Did you check grammar?  (ex. https://www.grammarly.com/, https://www.kiji-check.com/) 
- [X] Did you check pukiwiki grammar?
- [X] Did you check Japanese-English consistency?

2020-03-25 06:54 UTC, n-ando commented on documents/02_installation/01_install_1_2/03_java_1_2/05_check_windows_java_1_2/05_check_windows_java_1_2_en.txt
> +This sample set consists of RT components ConsoleIn and ConsoleOut.
RT components -> RT-Components

2020-03-25 06:55 UTC, n-ando requested changes
修正・確認お願いします。

2020-03-25 09:12 UTC, kkunita-work commented
修正しました。

2020-03-26 09:50 UTC, n-ando approved these changes

2020-03-26 09:50 UTC, merged