Windowsへのrtshellインストールでrtcwdコマンド確認を追加する
OpenRTM/openrtm.org pull request #258
Opened 2020-04-01 07:50 UTC by n-kawauchi

## Identify the Bug

Link to #257 

## Description of the Change

- Windowsへのrtshellインストールの項に、rtcwdコマンドの確認を追加した
- rtcwdコマンドを使えない場合、 rtshell_post_installを実行して使えるようにする手順を示した

## Verification 

- [ｘ] Did you check grammar?  (ex. https://www.grammarly.com/, https://www.kiji-check.com/) 
- [x] Did you check pukiwiki grammar?
- [x] Did you check Japanese-English consistency?

2020-04-02 02:56 UTC, n-ando commented on documents/02_installation/05_install_rtshell/01_howto_install/01_howto_install_en.txt
> + > rtcwd
英語のコマンドプロンプトでは以下のように表示されますので修正お願いします。

> rtcwd
'rtcwd' is not recognized as an internal or external command,
operable program or batch file.

2020-04-02 02:57 UTC, n-ando requested changes
rtcwdの英語説明の修正をお願いします。

2020-04-02 05:29 UTC, n-kawauchi commented
Drupalページも合わせて修正しました。

2020-04-06 01:19 UTC, n-ando approved these changes

2020-04-06 01:19 UTC, merged