Install pages sync
OpenRTM/openrtm.org pull request #41
Opened 2019-08-27 05:52 UTC by kkunita

## Identify the Bug

Link to the issue describing the bug that you're fixing.  
If there is not yet an issue for your bug, please open a new issue and then link to that issue in your pull request.

## Description of the Change
ドキュメント/インストール/`OpenRTMを10分...下
ドキュメント/インストール/1.2系のインストール　下
のWeb pageとの同期、およびDocumentMenu_ja.txtの追加変更(Document_jaは他の部分の変更内容も含みます。)

## Verification 

- [ ] Did you check grammar?  (ex. https://www.grammarly.com/, https://www.kiji-check.com/) 
- [X] Did you check pukiwiki grammar?
- [ ] Did you check Japanese-English consistency?

2019-08-28 13:31 UTC, kunita18 commented
#11

2019-08-29 03:26 UTC, n-ando requested changes
html直にコピーされているものが混ざってます。markdown形式で書いてください。

2019-08-29 07:19 UTC, n-ando commented
Documents/DocumentMenu_ja.md がHTMLになってしま言っています。Markdown形式をコミットしてください。

2019-08-29 07:53 UTC, kkunita commented
修正しました。

2019-08-29 07:59 UTC, n-ando approved these changes

2019-08-29 07:59 UTC, merged