Common install jdk8
OpenRTM/openrtm.org pull request #89
Opened 2019-11-19 02:25 UTC by kkunita

## Identify the Bug

新規ページ

## Description of the Change

JDK8のインストールについてまとめたページを作成。URLエイリアスはinstallation/commonの下とする。

## Verification 

- [X] Did you check grammar?  (ex. https://www.grammarly.com/, https://www.kiji-check.com/) 
- [X] Did you check pukiwiki grammar?
- [ ] Did you check Japanese-English consistency?

2019-11-19 07:30 UTC, n-ando requested changes
セクションを表す '*' の後にはスペースを空けてください。
pukiwikiのおおもとのパーサも、drupalに実装したパーサも、スペースなしでも正しくパースできますが、一般的にはスペースを空けることが多いので、スペースを空けるということで統一してください。
https://pukiwiki.osdn.jp/?FormattingRules#z15343da

「Webページからの配布元の例」の下のリストについてですが、改行 &br; や #br で極力整形はしないようにしてください。また、#br はブロック要素といって、以下のように行末に持ってきても本来は改行になりません。drupalのpukiwikiフィルタでは意図通り動くかもしれませんが。
詳しくは、以下のpukiwikiの整形ルールをご覧ください。
https://pukiwiki.osdn.jp/?FormattingRules#z15343da

あと、セクションの改装が深すぎます。せいぜい、"***" 3段くらいにしてください。

2019-11-19 10:12 UTC, kkunita commented
行頭の点が気になるので、#brを使いましたが、点なしでリストを作る方法があればよいのですが、ないようですね。気持ち悪いですが点付きのリストにするしかないんですかねぇ.. 段落にすると行間空きすぎですし...　まぁ、配布元のケースは、それほど気にはならないので、直すのは良いのですが...#90の方は、もう少し考えます。セクションの深さは、ちょっと文書の構造を考えなおします。

2019-11-26 02:27 UTC, kkunita commented
修正しました。

2019-11-27 05:15 UTC, n-ando approved these changes

2019-11-27 05:15 UTC, merged