Check windows java
OpenRTM/openrtm.org pull request #92
Opened 2019-11-21 05:10 UTC by kkunita

## Identify the Bug
特に大きな問題はなし

## Description of the Change

- 余分な空白の除去
- 細かい表現の変更

## Verification 

- [X] Did you check grammar?  (ex. https://www.grammarly.com/, https://www.kiji-check.com/) 
- [X] Did you check pukiwiki grammar?
- [ ] Did you check Japanese-English consistency?

2019-11-21 15:57 UTC, n-ando requested changes
#brで整形しないでください。その他、リストを使うなど修正お願いします。

2019-11-26 05:56 UTC, kkunita commented
#brはどこにもありません。最後の&brが意味なしだったので削除しました。

2019-11-27 05:23 UTC, n-ando commented
関係ないファイルへのコミットも含まれているようなので、それらは消してください。

2019-11-28 01:06 UTC, kkunita commented
一端クロースして、再PRします。それで関係ないファイルのは消えるかと思います。

2019-11-28 01:06 UTC, closed without merging